<?php

function Judul() {
    echo "<h2> Nama-Nama Hari: </h2>";
}

Judul();

// Mendeklarasikan array dengan benar
$hari[0] = "Senin";
$hari[1] = "Selasa";
$hari[2] = "Rabu";
$hari[3] = "Kamis";
$hari[4] = "Jum'at";
$hari[5] = "Sabtu";
$hari[6] = "Minggu";

echo "Daftar nama-nama hari: <br>";
echo "hari [0] = " . $hari[0] . "<br>";
echo "hari [1] = " . $hari[1] . "<br>";
echo "hari [2] = " . $hari[2] . "<br>";
echo "hari [3] = " . $hari[3] . "<br>";
echo "hari [4] = " . $hari[4] . "<br>";
echo "hari [5] = " . $hari[5] . "<br>";
echo "hari [6] = " . $hari[6] . "<br>";

?>